name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make the tar
      run: tar czf Client.tar.gz interface services docker.ts env.ts index.ts package.json package-lock.json tsconfig.json
    - name: Build the Docker image
    - uses: docker/build-push-action@v1
      with:
           username: YOURNAME
           password: ${{ secrets.GITHUB_TOKEN }}
           registry: docker.pkg.github.com
           repository: YOURNAME/publish-packages/game
           tag_with_sha: true
          
